owner: ChrisCarini # GitHub username
repo: upptime # Github repo name

# The sites to check for uptime
# https://upptime.js.org/docs/configuration/#endpoints
sites:
  - name: chriscarini.com
    url: https://chriscarini.com
  - name: jetbrains.chriscarini.com
    url: https://jetbrains.chriscarini.com
  - name: skypi.chriscarini.com
    url: https://skypi.chriscarini.com
  - name: blog.chriscarini.com
    url: https://blog.chriscarini.com
  
  - name: flask-over-fastcgi.demo.chriscarini.com
    url: https://flask-over-fastcgi.demo.chriscarini.com
  - name: flask-over-mod-rewrite.demo.chriscarini.com
    url: https://flask-over-mod-rewrite.demo.chriscarini.com
  - name: fastapi-over-fastcgi.demo.chriscarini.com
    url: https://fastapi-over-fastcgi.demo.chriscarini.com
  - name: fastapi-over-mod-rewrite.demo.chriscarini.com
    url: https://fastapi-over-mod-rewrite.demo.chriscarini.com
# Commenting out LinkedIn, as it will return a 'bad' status code (HTTP/999) despite being available.
#  - name: LinkedIn - Chris Carini
#    url: https://www.linkedin.com/in/chrisjcarini

# Users to assign downtime issues (optional)
# https://upptime.js.org/docs/configuration/#assignees
assignees:
  - ChrisCarini

# Configuration options for the static site
# https://upptime.js.org/docs/configuration/#status-website
status-website:
#   # Add your custom domain below, or remove the next line if you don't have a domain
#   cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Chris Carini's Upptime
  # To keep the page simple, commenting out the `introTitle` && `introMessage`.
#  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
#  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: "[Powered by open source]($REPO), [powered by Upptime](https://upptime.js.org)"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
